work to get to the main page, but something is missing/incorrect, get a C:\Users\artisd\Documents\personal\student\IGME.430.01-Rich Media Web App Dev II\w8-1-m\DomoMaker-A-Start\server\router. js:4     app.get('/login', controllers.Account.loginPage);                                           ^
TypeError: Cannot read property 'loginPage' of undefined
    at router (C:\Users\artisd\Documents\personal\student\IGME.430.01-Rich Media Web App Dev II\w8-1-m\DomoMaker-A-Start
\server\router.js:4:43)